### ISSUE TITLE
Integer i defined inside gmfCloseMesh function

### ISSUE THREAD

**Issue by dalphin5** [LoicMarechal/libMeshb#12]
Dear sir,

I just highlight the fact that the integer variable i of libMeshb7.c line 776 (commit 61eacd4) is defined inside the function gmfCloseMesh. Although it is correct with the C99 standard, I suggest to place this declaration at the beginning of the function because for it makes some IDE like Visual Studio complaining about it.

Regards.

Jeremy Dalphin

**Comment by LoicMarechal** [comment]
Hi Jeremy,
thanks for pointing that out.
I declared the "i" counter at the begginning of the procedure.
Regards,
Loïc
