### ISSUE TITLE
Example code in README.md might benefit from clarification that GmfFloat/GmfDouble is returned from GmfOpenMesh

### ISSUE THREAD

**Issue by Mathias-Fuchs** [LoicMarechal/libMeshb#22]
The example code in the README.md runs successfully only if Coords is an array of doubles, not floats (and there are some small typos).
EDIT: ok, just saw that GmfOpenMesh returns GmfFloat or GmfDouble in its third argument .... maybe that should be clear from the example, it's easy to assume that it will always paste sizeof(float) into the arguments of GmfSetLin.

**Comment by LoicMarechal** [comment]
> The example code in the README.md runs successfully only if Coords is an array of doubles, not floats (and there are some small typos).
> 
Hi Mathias,

thanks for pointing that out.
I corrected the typos to make the code compiling.
I specified that the "triangles.mesb" file should be written with single precision numbers.

Regards,

Loïc
