### ISSUE TITLE
VerticesOnGeometric Documentaion

### ISSUE THREAD

**Issue by mikepark** [LoicMarechal/libMeshb#8]
Hi Loic,

near line 985 of Documentation/libMeshb7.tex:
VerticesOnGeometricEdges has 1 real 
VerticesOnGeometricQuadrilaterals has 2 real
VerticesOnGeometricTriangles has 2 real

near line 286 of sources/libmeshb7.c: 
VerticesOnGeometricEdges is "iirr"
VerticesOnGeometricTriangles is "iirrr"
VerticesOnGeometricQuadrilaterals is "iirrr"

Would you please update the Documentation to include one more real? Would you like me to make a pull request for this change?

I am using these records to store CAD association data. I only need 1 real for edges (t) and 2 reals for triangles (u,v), but I wanted to re-use an existing record instead of creating a new type.

Thank you,
Mike

**Comment by LoicMarechal** [comment]
> Hi Loic,
> 
> near line 985 of Documentation/libMeshb7.tex:
> VerticesOnGeometricEdges has 1 real
> VerticesOnGeometricQuadrilaterals has 2 real
> VerticesOnGeometricTriangles has 2 real
> 
> near line 286 of sources/libmeshb7.c:
> VerticesOnGeometricEdges is "iirr"
> VerticesOnGeometricTriangles is "iirrr"
> VerticesOnGeometricQuadrilaterals is "iirrr"
> 
> Would you please update the Documentation to include one more real? Would you like me to make a pull request for this change?
> 
> I am using these records to store CAD association data. I only need 1 real for edges (t) and 2 reals for triangles (u,v), but I wanted to re-use an existing record instead of creating a new type.
> 
> Thank you,
> Mike
> 
> 


Hi Mike,
the extra real is used to store the distance from the geometrical entity the vertex is projected on.
I updated the github page.

Regards,

Loïc

**Comment by mikepark** [comment]
Thank you for clarification, You now have 3 reals listed in the document, but VerticesOnGeometricEdges is "iirr" or 2 integers and 2 reals.

**Comment by LoicMarechal** [comment]
> Thank you for clarification, You now have 3 reals listed in the document, but VerticesOnGeometricEdges is "iirr" or 2 integers and 2 reals.
> 
> 

My mistake, I corrected the documentation.

Loïc
